import { Video } from '@/types';

// Using placeholder UUIDs for mock data to simulate database entries
export const mockVideos: Video[] = [
  {
    id: 'c1b9b7b8-6c8a-4b1f-9e2b-1d1b1e1a1c1d',
    title: 'Building a UI Library from Scratch',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder1/hq720.jpg',
    channel_name: 'Dev Channel',
    created_at: '2023-01-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder1',
    channel_id: 'mock-channel-id',
    description: 'A detailed guide on building a UI library from scratch.',
    last_accessed_at: '2023-01-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'd2c0c8c9-7d9b-5c2g-0f3c-2e2c2f2b2d2e',
    title: 'The Future of Web Development',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder2/hq720.jpg',
    channel_name: 'CodeMasters',
    created_at: '2023-02-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder2',
    channel_id: 'mock-channel-id',
    description: 'Exploring the future trends in web development.',
    last_accessed_at: '2023-02-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'e3d1d9da-8ea-6d3h-1g4d-3f3d3g3c3e3f',
    title: 'React State Management in 2024',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder3/hq720.jpg',
    channel_name: 'ReactFanatics',
    created_at: '2023-03-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder3',
    channel_id: 'mock-channel-id',
    description: 'An overview of state management solutions for React.',
    last_accessed_at: '2023-03-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'f4e2e0eb-9fb-7e4i-2h5e-4g4e4h4d4f4g',
    title: 'A Guide to Tailwind CSS',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder4/hq720.jpg',
    channel_name: 'CSS Weekly',
    created_at: '2023-04-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder4',
    channel_id: 'mock-channel-id',
    description: 'Learn how to use Tailwind CSS effectively.',
    last_accessed_at: '2023-04-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'a5f3f1fc-0ac-8f5j-3i6f-5h5f5i5e5g5h',
    title: 'Introduction to Supabase',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder5/hq720.jpg',
    channel_name: 'BackendPro',
    created_at: '2023-05-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder5',
    channel_id: 'mock-channel-id',
    description: 'Getting started with Supabase for your backend needs.',
    last_accessed_at: '2023-05-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'b6a4a2ad-1bd-9g6k-4j7g-6i6g6j6f6h6i',
    title: 'Cooking the Perfect Steak',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder6/hq720.jpg',
    channel_name: 'Gourmet Chef',
    created_at: '2023-06-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder6',
    channel_id: 'mock-channel-id',
    description: 'A step-by-step guide to cooking the perfect steak.',
    last_accessed_at: '2023-06-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'c7b5b3be-2ce-0h7l-5k8h-7j7h7k7g7i7j',
    title: '10-Minute Morning Yoga',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder7/hq720.jpg',
    channel_name: 'YogaWithAdriana',
    created_at: '2023-07-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder7',
    channel_id: 'mock-channel-id',
    description: 'A quick 10-minute yoga routine to start your day.',
    last_accessed_at: '2023-07-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
  {
    id: 'd8c6c4cf-3df-1i8m-6l9i-8k8i8l8h8j8k',
    title: 'Exploring the Alps',
    thumbnail_url: 'https://i.ytimg.com/vi/placeholder8/hq720.jpg',
    channel_name: 'TravelVibes',
    created_at: '2023-08-01T00:00:00Z',
    user_id: 'mock-user-id',
    youtube_video_id: 'placeholder8',
    channel_id: 'mock-channel-id',
    description: 'A visual journey through the Alps.',
    last_accessed_at: '2023-08-01T00:00:00Z',
    channel_avatar_url: null,
    channel_description: null,
    profiles: null,
    is_from_channel_update: false,
  },
];

// Replace placeholder URLs with actual image URLs for better visuals
for (let i = 0; i < mockVideos.length; i++) {
    mockVideos[i].thumbnail_url = `https://source.unsplash.com/random/400x225?sig=${i}`;
    mockVideos[i].channel_avatar_url = `https://source.unsplash.com/random/40x40?face,person&sig=${i}`;
}